# Generated by Django 5.0.3 on 2024-10-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="balance",
            field=models.FloatField(default=0, max_length=255),
        ),
    ]
